### ISSUE TITLE
The airclimb check won't disable

### ISSUE THREAD

**Issue by maBelizario** [Rammelkast/AntiCheatReloaded#195] opened 2021-11-19 06:51 UTC
I disabled the airclimb check in the settings (checks.yml), but it's not disabled in game.
I tried both using the command '/acr reload' and restarting the server, but didn't work.

![image](https://user-images.githubusercontent.com/43346672/142577523-a175991a-6faf-489f-8c39-6ec82ae77fdc.png)
![image](https://user-images.githubusercontent.com/43346672/142577235-79107b1f-6d78-4dc3-8944-2850741edcd2.png)

**Comment by Rammelkast** [comment] 2021-11-19 13:18
Closed - duplicate of #190

**Closed by Rammelkast** 2021-11-19 13:18 UTC
