### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by f0xXx3r** [Rammelkast/AntiCheatReloaded#152] opened 2021-06-30 10:17 UTC
Hello!
I've found 2 bugs with your Anti Cheat Reloaded Plugin.

**#1** If you are under water and standing in Long Sea Grass if you press Jump and Sneak repeatedly
     the plugin will kick you out for fly hack.

**#2** If you use the Plugin Geyser, which allows you to play on a Java Server with Bedrock Edition,
     detects almost every movement as a cheat and blocks your movement and kicks you then for cheating.

Well thats what I found.

Have a great day/week/month! =)

Greetings

f0xx3r

**Comment by f0xXx3r** [comment] 2021-06-30 10:18
Ow just forgot im Playing on a Paper Server v1.17

**Comment by ENDER1355** [comment] 2021-07-01 11:05
> I'll have a look at number one. For number two, ACR does not support Geyser, and probably will not support it for some time.

Disable the anticheat for Geyser players?

**Comment by Rammelkast** [comment] 2021-07-02 15:25
@ENDER1355 I'll read into this. If it's easy enough to implement it will be in the next release.

**Comment by ENDER1355** [comment] 2021-07-02 17:46
> @ENDER1355 I'll read into this. If it's easy enough to implement it will be in the next release.

You need the Floodgate plugin.

**Comment by Rammelkast** [comment] 2021-07-03 10:39
Closing since this is now a duplicate of #142.

**Closed by Rammelkast** 2021-07-03 10:39 UTC
Labels: false-positive, high priority, unverified
