### ISSUE TITLE
100% & 120% speed bypass

### ISSUE THREAD

**Issue by kawaii-neverhide** [Rammelkast/AntiCheatReloaded#85] opened 2020-05-31 21:33 UTC
https://www.youtube.com/watch?v=eDAmqF3Hxpw

**Comment by Rammelkast** [comment] 2020-06-01 17:39
Can you give me some more information on how this works?

**Comment by kawaii-neverhide** [comment] 2020-06-01 22:03
> Can you give me some more information on how this works?

Video contains settings. It works like bad timer check && bad max speed && fast jump speed. Cubecraft fly just bad max speed check

**Comment by Rammelkast** [comment] 2020-06-04 14:43
Seen as duplicate of #73

**Closed by Rammelkast** 2020-06-04 14:43 UTC
Labels: bypass, duplicate
