### ISSUE TITLE
Player disconnect out of time (Lag Spikes)

### ISSUE THREAD

**Issue by killkillsito** [Rammelkast/AntiCheatReloaded#3] opened 2016-06-16 11:54 UTC
Hi! Im using your plugin AntiCheatReloaded, first of all thanks for this great plugin, but i have an issue..
It keeps kicking all my players, but not for hack related or false positives, the lose the connection...
It keeps spamming the console when a player disconnect so, i must to remove the console crash messages of the plugins with another one, here is the timings of the player connection with the plugin:
https://gyazo.com/cb7aa25f0a7f2aa9661d0ca721d4ec87
Thats was in my pvp server, and i get crashes in log about the plugin, and crashes like that:
[00:38:55] [Server thread/ERROR]: Could not pass event EntityShootBowEvent to AntiCheatReloaded v1.3.0-ALPHA-b27
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-PaperSpigot-"8b18730"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityShootBowEvent(CraftEventFactory.java:246) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.ItemBow.a(ItemBow.java:61) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.ItemStack.b(ItemStack.java:526) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.EntityHuman.bU(EntityHuman.java:109) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:608) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-"8b18730"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException

or this

[00:59:53] [Netty Epoll Server IO #0/ERROR]: [AntiCheatReloaded] Unhandled exception occured in onPacketReceiving(PacketEvent) for AntiCheatReloaded
java.lang.NullPointerException
	at net.gravitydevelopment.anticheat.check.movement.BlinkCheck$2.onPacketReceiving(BlinkCheck.java:51) ~[AntiCheatReloaded-1.3.0-ALPHA.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:3.6.6-SNAPSHOT-b224]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:3.6.6-SNAPSHOT-b224]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:639) [ProtocolLib.jar:3.6.6-SNAPSHOT-b224]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:606) [ProtocolLib.jar:3.6.6-SNAPSHOT-b224]
	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetReceived(NettyProtocolInjector.java:332) [ProtocolLib.jar:3.6.6-SNAPSHOT-b224]
	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketReceiving(NettyProtocolInjector.java:297) [ProtocolLib.jar:3.6.6-SNAPSHOT-b224]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.decode(NettyChannelInjector.java:546) [ProtocolLib.jar:3.6.6-SNAPSHOT-b224]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-PaperSpigot-"8b18730"]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:278) [ProtocolLib.jar:3.6.6-SNAPSHOT-b224]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
[00:59:53] [Netty Epoll Server IO #0/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook@3e45b6a6[
    x=-204.70600437546696
    y=69.24918707874468
    z=209.98605834948498
    yaw=443.39758
    pitch=30.300034
    f=false
    hasPos=true
    hasLook=true
  ]

But in my survival server i get crashes like this:
[16:39:59] [Server thread/ERROR]: Could not pass event BlockBreakEvent to AntiCheatReloaded v1.3.0-ALPHA-b27
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-PaperSpigot-"8b18730"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:215) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:640) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-"8b18730"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
	at net.gravitydevelopment.anticheat.util.BlockHardness.getHardness(BlockHardness.java:215) ~[?:?]
	at net.gravitydevelopment.anticheat.util.BlockHardness.getBlockHardness(BlockHardness.java:205) ~[?:?]
	at net.gravitydevelopment.anticheat.util.Utilities.calcSurvivalFastBreak(Utilities.java:377) ~[?:?]
	at net.gravitydevelopment.anticheat.check.Backend.checkFastBreak(Backend.java:496) ~[?:?]
	at net.gravitydevelopment.anticheat.event.BlockListener.onBlockBreak(BlockListener.java:78) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor404.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[spigot.jar:git-PaperSpigot-"8b18730"]
	... 18 more

**Comment by Rammelkast** [comment] 2016-06-16 13:12
The first error is cut off just after the Caused by:, that is the most important part, can you send that part?

**Comment by Rammelkast** [comment] 2016-06-16 13:14
Also, for the second error, you should delete your config and let it generate a new one.

**Comment by killkillsito** [comment] 2016-06-16 15:13
The timings? Here u go!
https://timings.aikar.co/v2/?id=ee2fcad393e14fa485f9f6106e95e2da#28_

**Comment by killkillsito** [comment] 2016-06-27 19:25
Any news?

**Comment by Rammelkast** [comment] 2016-07-17 18:01
The first error ends with **Caused by: java.lang.NullPointerException**, can you send what comes after that?

**Comment by Rammelkast** [comment] 2016-07-17 18:02
Also, the second error can be fixed by deleting magic.yml, and the third error is already fixed.

**Closed** 2016-07-23 17:30 UTC
Labels: bug
